# Generated by Django 4.1.1 on 2022-10-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BakedGood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("desc", models.TextField()),
                (
                    "good_type",
                    models.CharField(
                        choices=[
                            ("BR", "Bread"),
                            ("CA", "Cake"),
                            ("CO", "Cookie"),
                            ("PR", "Pretzel"),
                        ],
                        max_length=2,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("recipe", models.TextField()),
            ],
        ),
    ]
